# Generated by Django 5.1.2 on 2024-10-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ferramentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(max_length=255)),
                ('nome', models.TextField(max_length=255)),
                ('local', models.TextField(max_length=255)),
                ('instrutor', models.TextField(max_length=255)),
                ('status', models.TextField(max_length=255)),
            ],
        ),
    ]
